### ISSUE TITLE
Failed jobs aren't able to be deleted.

### ISSUE THREAD

**Issue by taylordaughtry** [lilt/craft-lilt-plugin#90]
Hi! I'm not able to delete failed jobs—it appears to be an issue with the Job not finding a TranslationRecord with the given ID. Here's a screenshot of the stack trace; _hopefully_ it's enough to diagnose, but happy to chat through this, if needed:

Based on a quick review, could it be that when the job is deleted the corresponding TranslationRecord is also deleted? (I.e. deleted via cascade). 

![Screenshot](https://cdn-std.droplr.net/files/acc_860000/G5Cjn5)

**Comment by tgallant** [comment]
Hi @taylordaughtry thanks for reporting. @hadomskyi could you take a look?

**Comment by hadomskyi** [comment]
Hey @taylordaughtry thanks. Yes seems like it can't find the id of deleted object, we will fix that. Thanks a lot for exception trace! :)

**Comment by hadomskyi** [comment]
Was fixed in [3.4.3](https://github.com/lilt/craft-lilt-plugin/releases/tag/3.4.3)
